<?php
	//-- command
	$sqlDatabase = "swdata";
	$sqlCommand = "SELECT SLAD_ID FROM ITSMSP_SLAD, CONFIG_RELI WHERE CONFIG_RELI.FK_PARENT_ID = ITSMSP_SLAD.FK_CMDB_ID AND CONFIG_RELI.FK_PARENT_TYPE = 'ME->SLA' AND FK_CHILD_TYPE = 'ME->THIRDPARTYCONTRACT' AND CONFIG_RELI.FK_CHILD_ID = ![contract:num]";
?>