<?php
	
	//ES
	$sqlDatabase = "swdata";
	$sqlCommand = "SELECT COMPANY.SUPPORTEXPIRYX, COMPANY.COMPANYNAME, COMPANY.PK_COMPANY_ID FROM USERDB, COMPANY, OPENCALL WHERE OPENCALL.CALLREF = '![in_callref]' AND USERDB.FK_COMPANY_ID = COMPANY.PK_COMPANY_ID AND OPENCALL.CUST_ID = USERDB.KEYSEARCH";
	
?>