<?php

	$sqlDatabase = "swdata";
	$sqlCommand= "select SC_FOLIO.SERVICE_NAME, SC_SUBSCRIPTION.TYPE, SC_SUBSCRIPTION.START_DATEX, SC_SUBSCRIPTION.FK_ME_DISPLAY, SC_FOLIO.FK_CMDB_ID, DEPARTMENT.PK_DEPT_CODE from SC_SUBSCRIPTION, DEPARTMENT, SC_FOLIO, CONFIG_ITEMI where DEPARTMENT.PK_DEPT_CODE = SC_SUBSCRIPTION.FK_ME_KEY and SC_FOLIO.FK_CMDB_ID = SC_SUBSCRIPTION.FK_SERVICE and CONFIG_ITEMI.PK_AUTO_ID = SC_SUBSCRIPTION.FK_SERVICE and DEPARTMENT.PK_DEPT_CODE = '![dept_code]' and (service_archived IS NULL OR service_archived != 1);";
	
?>